"""Structured plan generators for the report phase.

Pure-Python synthesis — no LLM, no Playwright.
Converts VulnReport → structured retest plan:
  - generate_retest_plan()          Structured retest checklist (RetestPlan)

Note: report.md and exec_summary.md are now generated by an LLM agent in
adversa/report/controller.py using the upstream phase artifacts as context.
"""

from __future__ import annotations

from datetime import UTC, datetime

from adversa.state.models import (
    RetestPlan,
    RetestStep,
    VulnReport,
)


_SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}

# Verification step templates keyed by vuln_type
_VERIFICATION_STEPS: dict[str, list[str]] = {
    "sql_injection": [
        "Reproduce the original vulnerability to confirm it exists.",
        "Apply the remediation (use parameterized queries or an ORM).",
        "Retry with payload `' OR 1=1--` and confirm no SQL error or unexpected data is returned.",
        "Confirm the query uses bound parameters in the code diff.",
    ],
    "reflected_xss": [
        "Reproduce the original vulnerability to confirm reflected XSS executes.",
        "Apply the remediation (escape output using context-appropriate encoding).",
        "Retry with payload `<script>alert(1)</script>` in the affected parameter.",
        "Confirm the payload is HTML-escaped in the response (e.g. `&lt;script&gt;`).",
    ],
    "stored_xss": [
        "Reproduce the original vulnerability to confirm stored XSS executes.",
        "Apply the remediation (escape on output, sanitize on input).",
        "Store the payload `<script>alert(1)</script>` via the affected input.",
        "Load the page that renders the stored content and confirm no script executes.",
    ],
    "dom_xss": [
        "Reproduce the DOM XSS in a browser with DevTools open.",
        "Apply the remediation (avoid innerHTML/eval; use textContent or DOMPurify).",
        "Retry with payload `<img src=x onerror=alert(1)>` and confirm no execution.",
        "Confirm safe DOM manipulation APIs are used in the code diff.",
    ],
    "ssrf": [
        "Reproduce the original SSRF to confirm the server fetches an attacker-controlled URL.",
        "Apply the remediation (allowlist permitted hosts; block metadata endpoints).",
        "Retry with `http://169.254.169.254/` and confirm the request is rejected.",
        "Confirm SSRF protection rejects private IP ranges and loopback addresses.",
    ],
    "idor": [
        "Reproduce the IDOR by accessing another user's resource ID and confirm unauthorized access.",
        "Apply the remediation (enforce server-side ownership check).",
        "Swap the resource ID to another user's ID and confirm HTTP 403 or 404 is returned.",
        "Confirm ownership enforcement is server-side, not client-side.",
    ],
    "broken_auth": [
        "Reproduce the authentication weakness to confirm it is exploitable.",
        "Apply the remediation (enforce strong auth, fix token validation, add rate limiting).",
        "Retry the authentication attack vector and confirm it fails.",
        "Confirm proper session invalidation on logout.",
    ],
    "session_fixation": [
        "Reproduce session fixation by setting a known session ID and confirming post-login acceptance.",
        "Apply the remediation (regenerate session ID on successful authentication).",
        "Confirm a new session ID is issued after login.",
        "Verify the old session ID is invalidated.",
    ],
    "command_injection": [
        "Reproduce the command injection with a benign payload (e.g. `; id`).",
        "Apply the remediation (avoid shell=True; use subprocess with an argument list).",
        "Retry with `; id` and confirm no command output is returned.",
        "Confirm input is not passed to shell execution functions.",
    ],
    "template_injection": [
        "Reproduce template injection with payload `{{7*7}}` and confirm `49` is returned.",
        "Apply the remediation (use sandboxed rendering or escape user input).",
        "Retry with `{{7*7}}` and confirm the expression is not evaluated.",
        "Confirm template engine sandboxing is enabled.",
    ],
    "path_traversal": [
        "Reproduce path traversal with `../../../../etc/passwd` payload.",
        "Apply the remediation (canonicalize paths and validate against the allowed base directory).",
        "Retry with the traversal payload and confirm access is denied.",
        "Confirm `Path.resolve()` or equivalent is used before file access.",
    ],
    "xxe": [
        "Reproduce XXE with an external entity injection payload.",
        "Apply the remediation (disable external entity processing in the XML parser).",
        "Retry with the XXE payload and confirm external entities are not resolved.",
        "Confirm the XML parser has `FEATURE_EXTERNAL_GENERAL_ENTITIES` disabled.",
    ],
}
_DEFAULT_VERIFICATION_STEPS = [
    "Reproduce the original vulnerability to confirm it exists.",
    "Apply the recommended remediation.",
    "Retry the original attack vector and confirm the vulnerability is no longer exploitable.",
]


def generate_retest_plan(vuln_report: VulnReport) -> RetestPlan:
    """Generate a structured retest plan — one RetestStep per finding, ordered by severity."""
    all_findings = sorted(vuln_report.all_findings, key=lambda f: _SEVERITY_ORDER.get(f.severity, 99))
    now = datetime.now(UTC).isoformat()

    steps: list[RetestStep] = []
    for i, finding in enumerate(all_findings, start=1):
        endpoint = finding.endpoint
        if finding.method:
            endpoint = f"{finding.method} {finding.endpoint}"

        vuln_type_key = finding.vuln_type.lower()
        verification_steps = _VERIFICATION_STEPS.get(vuln_type_key, _DEFAULT_VERIFICATION_STEPS)

        steps.append(
            RetestStep(
                id=f"RETEST-{i:03d}",
                finding_id=finding.id,
                endpoint=endpoint,
                method=finding.method,
                vulnerability_type=finding.vuln_type,
                severity=finding.severity,
                parameter=finding.parameter,
                remediation_summary=finding.remediation,
                verification_steps=list(verification_steps),
                pass_criteria=finding.remediation,
            )
        )

    return RetestPlan(
        target_url=vuln_report.target_url,
        generated_at=now,
        total_findings=len(all_findings),
        retest_steps=steps,
    )
